/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vowelcounterapp;

import java.awt.Component;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.TimerTask;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import static java.util.concurrent.TimeUnit.HOURS;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author Alankrit
 */

public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    File files[]=new File[100];
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jLabel1);

        jScrollPane2.setViewportView(jLabel2);

        jButton1.setText("Files");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Process");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Help");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,
    "Select the files in the dialogue box using Files and then click proocess to calculate vowels !",
    "Help",
    JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
chooser.setMultiSelectionEnabled(true);
chooser.showOpenDialog((JFrame) SwingUtilities.getWindowAncestor(this));
files = chooser.getSelectedFiles();
String str[]=new String[100];
for(int i=0;files.length>i;i++)
{str[i]=files[i].getName();System.out.println(str[i]);}
JList<String> jlist1= new JList(str);
//jScrollPane1= new JScrollPane((Component) Arrays.asList(jlist1));
        DefaultListModel listModel = new DefaultListModel();
//for(int i=0;i<files.length;i++)
//listModel.addElement(files[i].getName());
//jList1=new JList(listModel);
//jList1.setVisible(true);
/*if(files.length >= 2) {
    compare(readFileAsList(files[0]), readFileAsList(files[1]));
}*/
        String s="";
        for(int i=0;i<files.length;i++)
            s=s+files[i].getName()+"<br>";
        jLabel1.setText("<HTML>"+s+"</HTML>");
        System.out.println("LABEL SHOULD BE : "+getfilelistasstring());
    }//GEN-LAST:event_jButton1ActionPerformed
String getfilelistasstring()
{
String s="";
for(int i=0;i<files.length;i++)
    s=s+files[i].getName()+"\n";
return s;//

}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        vcount="";
         ExecutorService threadPool = Executors.newFixedThreadPool(10);
 // submit jobs to be executing by the pool
  Thread[] threads = new Thread[files.length];
 for (int i = 0; i < threads.length; i++) {
     final File f= files[i];
     threads[i] = new Thread(new Runnable() {
         public void run() {
             try {
                 // some code to run in parallel
                 numvowels(f);
             } catch (FileNotFoundException ex) {
                 Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
             }
         }
     });
     threads[i].start();
 }
 
   final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
        Runnable yourRunnable= new Runnable() {

            @Override
            public void run() {
                jLabel2.setText("<HTML>"+vcount+"</HTML>");
                //To change body of generated methods, choose Tools | Templates.
            }
        };
 scheduler.scheduleAtFixedRate(yourRunnable, 0, 100, TimeUnit.MILLISECONDS);
        
 
 
 
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

   
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
        new NewJFrame().setVisible(true);
       
    }//GEN-LAST:event_jButton3ActionPerformed
    
    String vcount;
    private void numvowels(File file) throws FileNotFoundException
    {
    Scanner input = new Scanner(file);
    
        // Create the Content String        
        String fileContent = "";

        // Read data from a file
        while (input.hasNext()) {
            fileContent += input.next() + " ";
        }
        // Close the file
        input.close();

        //Split the string into a character array
        char[] charArr = fileContent.toCharArray();
        
        //loop through every character to find the vowels
        int counter = 0;
        for(char c : charArr)
        {
              if(c == 'a' || c == 'e' || c == 'i' || c == 'o' || c == 'u' )
                   counter++;
        }
       
        //Tell the user the number of vowels
        System.out.println("Number of Vowels in" + file.getName()+" : " + counter);
        vcount=vcount+"Number of Vowels in" + file.getName()+" : " + counter+"<br>";
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
